server:
  port: 8080

web:
  # 基于项目的根目录设置相对路径, 在项目启动时需要创建该文件夹
  upload-path: ./uploads/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/open_course
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.PostgreSQL92Dialect
  show-sql: true
  properties:
    hibernate:
      temp:
        use_jdbc_metadata_defaults: true
  servlet:
    multipart:
      max-file-size: 10MB # 单个最大文件大小
      max-request-size: 100MB # 总请求文件大小
  resources:
    # 除了带上Spring Boot的默认静态资源路径之外， 加上file:${web.upload-path}指向外部问卷资源上传路径
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}

logging:
  level:
    root: WARN
    com.example.openCourse: DEBUG
  file:
    name: myapp.log
